import { TextFieldProps } from '../../types';

/**
 *   the default properties for the text field component
 */
export const defaultProps: TextFieldProps = {
  variant: 'outlined',
  showClearButton: true,
  noDefaultErrorMessage: false,
  inputMode: undefined,
  onPressIn: undefined,
  onPressOut: undefined,
  id: undefined,
  onPointerEnter: undefined,
  onPointerEnterCapture: undefined,
  onPointerLeave: undefined,
  onPointerLeaveCapture: undefined,
  onPointerMove: undefined,
  onPointerMoveCapture: undefined,
  onPointerCancel: undefined,
  onPointerCancelCapture: undefined,
  onPointerDown: undefined,
  onPointerDownCapture: undefined,
  onPointerUp: undefined,
  onPointerUpCapture: undefined,
  'aria-label': undefined,
  'aria-busy': undefined,
  'aria-checked': undefined,
  'aria-disabled': undefined,
  'aria-expanded': undefined,
  'aria-selected': undefined,
  'aria-labelledby': undefined,
  'aria-valuemax': undefined,
  'aria-valuemin': undefined,
  'aria-valuenow': undefined,
  'aria-valuetext': undefined,
  'aria-hidden': undefined,
  'aria-live': undefined,
  'aria-modal': undefined,
  role: undefined,
  autoComplete: undefined,
  cursorColor: undefined,
  verticalAlign: undefined,
  label: 'Text Field',
  href: undefined,
  hrefAttrs: undefined,
  onClick: undefined,
  accessibilityLabelledBy: undefined,
  accessibilityLanguage: undefined,
  numberOfLines: 1,
};
